-- DB integrity review fixes.
--
-- 1) Dedupe PosCheck rows before enforcing webhook idempotency (keep newest).
DELETE FROM "PosCheck" a
USING "PosCheck" b
WHERE a."id" < b."id"
  AND a."venueId" = b."venueId"
  AND a."provider" = b."provider"
  AND a."externalCheckId" = b."externalCheckId";

-- 2) Purge orphaned rows (their venue no longer exists) so the new FK
--    constraints can be applied. These rows are unreachable garbage.
DELETE FROM "ScheduleTemplate" WHERE "venueId" NOT IN (SELECT "id" FROM "Venue");
DELETE FROM "NotificationRead" WHERE "venueId" NOT IN (SELECT "id" FROM "Venue");
DELETE FROM "Waitlist" WHERE "venueId" NOT IN (SELECT "id" FROM "Venue");
DELETE FROM "TableAssignment" WHERE "venueId" NOT IN (SELECT "id" FROM "Venue");
DELETE FROM "PosConnection" WHERE "venueId" NOT IN (SELECT "id" FROM "Venue");
DELETE FROM "PosLaborPunch" WHERE "venueId" NOT IN (SELECT "id" FROM "Venue");
DELETE FROM "CrmActivityLog" WHERE "venueId" NOT IN (SELECT "id" FROM "Venue");
DELETE FROM "PaymentMethod" WHERE "venueId" NOT IN (SELECT "id" FROM "Venue");
DELETE FROM "Invoice" WHERE "venueId" NOT IN (SELECT "id" FROM "Venue");
DELETE FROM "VenueRole" WHERE "venueId" NOT IN (SELECT "id" FROM "Venue");
DELETE FROM "Team" WHERE "venueId" NOT IN (SELECT "id" FROM "Venue");
DELETE FROM "ScheduleEmailEvent" WHERE "venueId" NOT IN (SELECT "id" FROM "Venue");
DELETE FROM "PayrollExport" WHERE "venueId" NOT IN (SELECT "id" FROM "Venue");
DELETE FROM "ReservationConnection" WHERE "venueId" NOT IN (SELECT "id" FROM "Venue");
DELETE FROM "ReservationSyncEvent" WHERE "venueId" NOT IN (SELECT "id" FROM "Venue");
DELETE FROM "BarInventoryItem" WHERE "venueId" NOT IN (SELECT "id" FROM "Venue");
DELETE FROM "BarInventoryMovement" WHERE "venueId" NOT IN (SELECT "id" FROM "Venue");
DELETE FROM "ManagerGoal" WHERE "venueId" NOT IN (SELECT "id" FROM "Venue");
DELETE FROM "VenueEvent" WHERE "venueId" NOT IN (SELECT "id" FROM "Venue");
DELETE FROM "ReservationSetting" WHERE "venueId" NOT IN (SELECT "id" FROM "Venue");
DELETE FROM "TableStateHistory" WHERE "venueId" NOT IN (SELECT "id" FROM "Venue");
DELETE FROM "Invite" WHERE "venueId" NOT IN (SELECT "id" FROM "Venue");

-- 3) Schema changes generated by prisma migrate diff:
-- DropForeignKey
ALTER TABLE "Message" DROP CONSTRAINT "Message_senderId_fkey";

-- DropForeignKey
ALTER TABLE "TimeEntry" DROP CONSTRAINT "TimeEntry_profileId_fkey";

-- DropIndex
DROP INDEX "PosCheck_venueId_provider_externalCheckId_idx";

-- DropIndex
DROP INDEX "SubscriptionEvent_source_externalEventId_idx";

-- AlterTable
ALTER TABLE "Venue" ADD COLUMN     "timezone" TEXT;

-- AlterTable
ALTER TABLE "Message" ALTER COLUMN "senderId" DROP NOT NULL;

-- AlterTable
ALTER TABLE "TimeEntry" ADD COLUMN     "profileFullName" TEXT,
ALTER COLUMN "profileId" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Reservation" DROP COLUMN "depositAmount";

-- CreateIndex
CREATE UNIQUE INDEX "PosCheck_venueId_provider_externalCheckId_key" ON "PosCheck"("venueId", "provider", "externalCheckId");

-- AddForeignKey
ALTER TABLE "ScheduleTemplate" ADD CONSTRAINT "ScheduleTemplate_venueId_fkey" FOREIGN KEY ("venueId") REFERENCES "Venue"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Message" ADD CONSTRAINT "Message_senderId_fkey" FOREIGN KEY ("senderId") REFERENCES "Profile"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "NotificationRead" ADD CONSTRAINT "NotificationRead_venueId_fkey" FOREIGN KEY ("venueId") REFERENCES "Venue"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TimeEntry" ADD CONSTRAINT "TimeEntry_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "Profile"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Waitlist" ADD CONSTRAINT "Waitlist_venueId_fkey" FOREIGN KEY ("venueId") REFERENCES "Venue"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TableAssignment" ADD CONSTRAINT "TableAssignment_venueId_fkey" FOREIGN KEY ("venueId") REFERENCES "Venue"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PosConnection" ADD CONSTRAINT "PosConnection_venueId_fkey" FOREIGN KEY ("venueId") REFERENCES "Venue"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PosLaborPunch" ADD CONSTRAINT "PosLaborPunch_venueId_fkey" FOREIGN KEY ("venueId") REFERENCES "Venue"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CrmActivityLog" ADD CONSTRAINT "CrmActivityLog_venueId_fkey" FOREIGN KEY ("venueId") REFERENCES "Venue"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PaymentMethod" ADD CONSTRAINT "PaymentMethod_venueId_fkey" FOREIGN KEY ("venueId") REFERENCES "Venue"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Invoice" ADD CONSTRAINT "Invoice_venueId_fkey" FOREIGN KEY ("venueId") REFERENCES "Venue"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VenueRole" ADD CONSTRAINT "VenueRole_venueId_fkey" FOREIGN KEY ("venueId") REFERENCES "Venue"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Team" ADD CONSTRAINT "Team_venueId_fkey" FOREIGN KEY ("venueId") REFERENCES "Venue"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ScheduleEmailEvent" ADD CONSTRAINT "ScheduleEmailEvent_venueId_fkey" FOREIGN KEY ("venueId") REFERENCES "Venue"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PayrollExport" ADD CONSTRAINT "PayrollExport_venueId_fkey" FOREIGN KEY ("venueId") REFERENCES "Venue"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ReservationConnection" ADD CONSTRAINT "ReservationConnection_venueId_fkey" FOREIGN KEY ("venueId") REFERENCES "Venue"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ReservationSyncEvent" ADD CONSTRAINT "ReservationSyncEvent_venueId_fkey" FOREIGN KEY ("venueId") REFERENCES "Venue"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "BarInventoryItem" ADD CONSTRAINT "BarInventoryItem_venueId_fkey" FOREIGN KEY ("venueId") REFERENCES "Venue"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "BarInventoryMovement" ADD CONSTRAINT "BarInventoryMovement_venueId_fkey" FOREIGN KEY ("venueId") REFERENCES "Venue"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ManagerGoal" ADD CONSTRAINT "ManagerGoal_venueId_fkey" FOREIGN KEY ("venueId") REFERENCES "Venue"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VenueEvent" ADD CONSTRAINT "VenueEvent_venueId_fkey" FOREIGN KEY ("venueId") REFERENCES "Venue"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ReservationSetting" ADD CONSTRAINT "ReservationSetting_venueId_fkey" FOREIGN KEY ("venueId") REFERENCES "Venue"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TableStateHistory" ADD CONSTRAINT "TableStateHistory_venueId_fkey" FOREIGN KEY ("venueId") REFERENCES "Venue"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Invite" ADD CONSTRAINT "Invite_venueId_fkey" FOREIGN KEY ("venueId") REFERENCES "Venue"("id") ON DELETE CASCADE ON UPDATE CASCADE;
node.exe : ┌─────────────────────────────────────────────────────────┐
At line:1 char:1
+ & "C:\Program Files\nodejs/node.exe" "C:\Program Files\nodejs/node_mo ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (┌──────────────...──────────────┐:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
│  Update available 6.19.3 -> 7.8.0                       │
│                                                         │
│  This is a major update - please follow the guide at    │
│  https://pris.ly/d/major-version-upgrade                │
│                                                         │
│  Run the following to update                            │
│    npm i --save-dev prisma@latest                       │
│    npm i @prisma/client@latest                          │
└─────────────────────────────────────────────────────────┘


