import { Controller, Get } from '@nestjs/common';

const convexSurface = {
  app: [
    'bootstrapProfile',
    'registerVenue',
    'getMe',
    'updateVenue',
    'getMyVenueBilling',
    'getDashboard',
    'getClockBoard',
    'getMyTimeClock',
    'clockIn',
    'clockOut',
    'listStaffRequests',
    'createStaffRequest',
    'reviewStaffRequest',
    'listVenueStaff',
    'upsertVenueStaff',
    'deactivateVenueStaff',
    'getNotifications',
    'markNotificationRead',
    'getManagerInsights',
    'deleteMyAccount',
    'exportTimeEntriesCsv',
  ],
  crm: ['listLeads', 'getLead', 'listBeos', 'listContracts', 'saveLead', 'addNote', 'saveBeo', 'saveContract', 'convertBeoToContract', 'deleteLead'],
  scheduling: [
    'getMyAvailability',
    'setMyAvailability',
    'listBlackouts',
    'addBlackout',
    'removeBlackout',
    'getManagerSchedule',
    'previewAutoSchedule',
    'applyAutoSchedule',
    'createShift',
    'updateShift',
    'assignShift',
    'unassignShift',
    'deleteShift',
    'getMySchedule',
    'claimOpenShift',
    'requestDropShift',
    'publishSchedule',
    'setLaborBudget',
    'listScheduleTemplates',
    'saveScheduleTemplate',
    'applyScheduleTemplate',
    'deleteScheduleTemplate',
    'copyDayShifts',
    'clearWeek',
    'restoreShifts',
    'proposeShiftSwap',
    'respondToShiftSwap',
    'reviewShiftSwap',
    'getMyShiftSwaps',
    'listShiftSwaps',
  ],
  floor: ['getActiveFloorPlan', 'getFloorStats', 'getTableHistory', 'saveFloorPlan', 'clearActiveFloorPlan'],
  floorBinding: [
    'getActiveFloorPlan',
    'getTableTimeline',
    'getUnassignedReservations',
    'getOpenWaitlist',
    'addToWaitlist',
    'markWaitlistReady',
    'removeFromWaitlist',
    'assignReservationToTables',
    'assignWaitlistToTables',
    'releaseAssignment',
  ],
  tables: ['updateTableState', 'seatParty', 'markDirty', 'markClean', 'transferTable', 'mergeTables', 'mergeTablesForParty', 'splitMergedTables'],
  chat: ['ensureChatSetup', 'createGroup', 'listConversations', 'listDirectory', 'openDm', 'getMessages', 'sendMessage', 'deleteConversation'],
  guests: ['listGuests', 'getGuestProfile', 'upsertGuest', 'ingestLeads', 'rotateLeadsWebhookSecret', 'removeGuest'],
  reservations: ['getReservationsPage', 'saveReservationSettings', 'saveReservation', 'removeReservation', 'exportReservationsCsv'],
  pos: ['getPosOverview', 'getSalesSummaryDashboard', 'getSalesByServer', 'getTopMenuItems', 'getLaborSummary', 'upsertPosConnection', 'importPosCheck'],
  payroll: ['getPayrollSummary', 'exportPayrollCsv', 'recordPayrollExport'],
  billing: ['getMyBilling', 'createStripeCheckoutSession', 'createStripeBillingPortalSession'],
  push: ['registerPushToken', 'disablePushToken', 'getMyPushTokens'],
};

@Controller('v1/compatibility')
export class CompatibilityController {
  @Get('convex-surface')
  getConvexSurface() {
    return {
      status: 'migration-in-progress',
      modules: convexSurface,
      totalFunctions: Object.values(convexSurface).reduce((total, functions) => total + functions.length, 0),
    };
  }
}
